---
deployment:
      tasks:
          - export DEPLOYPATH=/home3/shresthasarojcom/test/    # deploypath
          - export PUBLICPATH=/home3/shresthasarojcom/test.shrestha-saroj.com.np/

          - /bin/cp -r * $DEPLOYPATH                    
          - /bin/rm -Rf /home3/shresthasarojcom/test/public

          - /bin/cp -r /home3/shresthasarojcom/test_env/.env $DEPLOYPATH  

          - /bin/rm -Rf /home3/shresthasarojcom/test.shrestha-saroj.com.np/
          - /bin/cp -r public $PUBLICPATH
          
          - /bin/cp -r /home3/shresthasarojcom/test_env/index.php $PUBLICPATH  
