---
deployment:
      tasks:
          - export DEPLOYPATH=/home/themo841/order/    # deploypath
          - export PUBLICPATH=/home/themo841/order.themomostation.ca/  # publicpath

          - /bin/cp -r * $DEPLOYPATH                    
          - /bin/rm -Rf /home/themo841/order/public

          - /bin/cp -r /home/themo841/backup_env/.env $DEPLOYPATH  

          - /bin/rm -Rf /home/themo841/order.themomostation.ca/
          - /bin/cp -r public $PUBLICPATH
          
          - /bin/cp -r /home/themo841/backup_env/index.php $PUBLICPATH  
