---
deployment:
      tasks:
          - export DEPLOYPATH=/home3/shresthasarojcom/test/    # deploypath
          - export PUBLICPATH=/home3/shresthasarojcom/test.shrestha-saroj.com.np/

          - /bin/cp -r * $DEPLOYPATH                     #copy all recursively to $DEPLOYPATH

           - /bin/rm -Rf /home3/shresthasarojcom/test.shrestha-saroj.com.np/*  #remove all files in a the directory
          - /bin/cp -R public/ $PUBLICPATH    
